volumes:
  postgres_data:

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: postres
      POSTGRES_DB: postres
    ports:
      - "8089:5432"
