version: '3.9'

services:
  main-backend:
    build:
      dockerfile: PetSitters_backend/Dockerfile
    container_name: pet-backend
    ports: 
      - "${API_PORT}:8001"
    command: "uvicorn application.api.main:app --reload --host 0.0.0.0 --port 8001"
    env_file:
      - .env

  main-frontend:
    build:
      dockerfile: PetSitters_front/Dockerfile
    container_name: pet-frontend
    ports:
      - "8000:8000"
    command: "yarn dev"